Filter improvements
ThreeSixtyGiving/registry pull request #119
Opened 2022-08-02 18:00 UTC by Lathrisk

#113

Pending sign off

2022-08-09 15:47 UTC, Lathrisk commented
This updates the back to all publishers copy on the publisher page nav button.

![360-back-to-all](https://user-images.githubusercontent.com/517804/183698302-651fae59-e9eb-49a9-8175-3f0daab3e63e.png)

And adds a multi-select filter box for all publishers using the vue-select library. A clear all button has also been added that removes all selections.

![360-filters](https://user-images.githubusercontent.com/517804/183698450-cc0e6219-c560-403a-a2f0-19ad0991b43e.png)

2022-08-10 13:41 UTC, michaelwood requested changes
All the code looks good to me, one minor thing could we change `publisherParams` to something more friendly as we're exposing that in the url.

As we're now changing the filter functionality to be on the client side and we're not just rendering the output I think we're now in the "really need a selenium test" threshold. vue select looks well tested so only looking for a basic test for the code in the app.

2022-08-10 14:24 UTC, Lathrisk commented
@michaelwood I've updated the URL parameter to just `publishers`, while keeping publisherParams in the code.

In terms of tests. I suspect we want to separate the vue testing from the flask testing in case we want to split them in future, so is selenium the best choice for that? It looks like nightwatch.js is the bundled e2e testing tool for vue-cli. There are other options too, but if we want to keep testing consistency with other parts of 360 then we can use selenium.

2022-08-16 13:57 UTC, michaelwood commented on tests_dashboard/test_dashboard.py
> +    browser.get(url_for('dashboard', _external=True) + 'publishers?publisherParams=360G-BNG&publisherParams=360G-coopgroup')
Is publisherParams correct here? Given the change in the url schema to publisher= ?

2022-08-16 13:58 UTC, michaelwood requested changes
One comment on the Is publisherParams correct here: https://github.com/ThreeSixtyGiving/registry/blob/filter-improvements/tests_dashboard/test_dashboard.py#L39 . If you can squash the vue rebuilds before you merge it that'd be nice too.

2022-08-16 14:05 UTC, Lathrisk commented on tests_dashboard/test_dashboard.py
> +    browser.get(url_for('dashboard', _external=True) + 'publishers?publisherParams=360G-BNG&publisherParams=360G-coopgroup')
Yeah, the base is old, updating now.

2022-08-16 14:06 UTC, michaelwood commented on tests/test_functional.py
> +from selenium.webdriver.common.by import By
:+1:

2022-08-16 14:32 UTC, michaelwood approved these changes

2022-08-16 14:34 UTC, merged