matomo: Add cookie expiry
ThreeSixtyGiving/registry pull request #133
Opened 2023-04-03 13:56 UTC by codemacabre

2023-04-03 16:29 UTC, michaelwood requested changes

2023-04-03 16:29 UTC, michaelwood commented on registry/templates/vue-build/index.html
> +        document.cookie = "noEnhancedAnalytics=1 ;max-age=60*60*24*30 ;domain=threesixtygiving.org";
Are you sure the max-age part of the string "60*60*24*30" gets evaluated as a calculation?

2023-04-03 16:35 UTC, codemacabre commented on registry/templates/vue-build/index.html
> +        document.cookie = "noEnhancedAnalytics=1 ;max-age=60*60*24*30 ;domain=threesixtygiving.org";
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie) suggests it does, but on checking elsewhere it seems it only accepts milliseconds. I'll fix.

2023-04-04 07:16 UTC, michaelwood approved these changes

2023-04-04 07:18 UTC, merged