Licence icons
ThreeSixtyGiving/registry pull request #134
Opened 2023-04-25 08:06 UTC by codemacabre

## Summary
+ Upgrade engine to Node 18.16.0 (LTS)
+ Upgrade dependencies to be compatible with Node 18.16.0
+ Set ESlint rules to warn to avoid breaking build
+ Fix asset path in CSS (temporary)
+ Add image assets
+ Display licence icons for all licence types

## Verify
1. Search for a publisher
2. Select 'See More'
3. Licence icons should now display in the 'Licence' field

Fixes: https://github.com/ThreeSixtyGiving/registry/issues/84

2023-04-25 14:38 UTC, michaelwood requested changes

2023-04-25 14:38 UTC, michaelwood commented on registry-vue/src/assets/styles/main.css
> +      background: url("../images/checkmark-icon.svg") no-repeat;
Is this file part of the design system? I think it might be- changing it here would get overwritten when the css file is next rebuilt. https://github.com/ThreeSixtyGiving/360-ds/blob/master/src/components/03-components/filter-list/filter-list.scss#L89 ?

2023-04-25 14:38 UTC, michaelwood commented on registry-vue/package.json
> +    "node": ">= 18.16.0"
Can the github workflow file be updated to reflect this too. https://github.com/ThreeSixtyGiving/registry/blob/dashboard/.github/workflows/test_dashboard.yml#L12

2023-05-02 05:37 UTC, codemacabre commented on registry-vue/src/assets/styles/main.css
> +      background: url("../images/checkmark-icon.svg") no-repeat;
Updated in https://github.com/ThreeSixtyGiving/360-ds/pull/98

2023-05-09 16:29 UTC, michaelwood commented
Test looks like it's failing because we're getting blocked by twitter via a 403 http status code. I think it's fine to put something like:

```diff
for link in links:
+   # twitter blocking requests
+    if "twitter" in link.get_attribute("href"):
+        continue
```
in https://github.com/ThreeSixtyGiving/registry/blob/dashboard/tests/test_functional.py#L139 to skip over that one.

2023-05-11 14:14 UTC, michaelwood requested changes
* One tiny change to the Footer.vue 
* The badges filter doesn't resume state from the URL GET parameters in the same way as the publisher filter does, to test this filter to some badges, press refresh or filter some badges and copy paste a URL into a new window. e.g. http://localhost:8081/publishers?badges=hasGrantClassification

2023-05-11 14:14 UTC, michaelwood commented on registry-vue/src/components/home/parts/Footer.vue
is this part of https://github.com/ThreeSixtyGiving/registry/issues/122 ? If we don't need the code definitely remove it rather than comment it out, it's always in the git history if we needed it back.

2023-05-11 14:21 UTC, codemacabre commented on registry-vue/src/components/home/parts/Footer.vue
Whoops, that was an oversight. Removed.

2023-05-11 15:58 UTC, michaelwood requested changes
I'm seeing something odd going on with this, it works with one badge but not multiples. I'm also wondering if the expected behaviour is to filter using AND and not OR.  Worth checking I think.

2023-05-11 15:58 UTC, michaelwood requested changes
I'm seeing something odd going on with this, it works with one badge but not multiples. I'm also wondering if the expected behaviour is to filter using AND and not OR.  Worth checking I think.

2023-05-11 15:58 UTC, michaelwood requested changes
I'm seeing something odd going on with this, it works with one badge but not multiples. I'm also wondering if the expected behaviour is to filter using AND and not OR.  Worth checking I think.

2023-05-11 15:58 UTC, michaelwood requested changes
I'm seeing something odd going on with this, it works with one badge but not multiples. I'm also wondering if the expected behaviour is to filter using AND and not OR.  Worth checking I think.

2023-05-15 19:24 UTC, michaelwood approved these changes

2023-05-15 19:47 UTC, michaelwood commented
Thanks for all this work. Work combined into #141 . Future improvements and developments can now be done in a branch off of "dashbaord" branch.

2023-05-15 19:47 UTC, closed without merging